export const FETCH_LOCATION_REQUEST = "FETCH_LOCATION_REQUEST";
export const FETCH_LOCATION_SUCCESS = "FETCH_LOCATION_SUCCESS";
export const FETCH_LOCATION_FAILURE = "FETCH_LOCATION_FAILURE";
export const DELETE_SEARCH_LIST = "DELETE_SEARCH_LIST";
export const DELETE_ALL = "DELETE_ALL";
